### ISSUE TITLE
How to use LogGPT?

### ISSUE THREAD

**Issue by guoqiangqi** [nokia/LogGPT#1]
I have no idea how to use LogGPT for my production according to provided messages, should i train the model by myself first or already have some trained model i can download and deploying?

**Comment by medtray** [comment]
Thank you for your question. Yes, the model should be first trained using your new data, because the model is trained based on data-specific templates that are computed with Drain. As a follow-up work, we are trying to overcome the limitations of the data-specific templates :)

**Comment by kamui-fin** [comment]
Hi @medtray , I was wondering how the follow-up work is going? Currently, we're having to pre-train on existing known logs separately for each service before deploying, so I would love to hear about any updates the Nokia team has on LogGPT.
